version: 2
jobs:
  build:
    working_directory: ~/pfm-app
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - pfm-app-maven-{{ checksum "pom.xml" }}
            - pfm-app-node-{{ checksum "package.json" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pfm-app-maven-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/pfm-app/src/webapp/node_modules
          key: pfm-app-node-{{ checksum "~/pfm-app/src/webapp/package.json" }}
      - store_artifacts:
          path: target/spring-boot-react-0.0.1-SNAPSHOT.jar
  deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/pfm-app
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml"}}
    - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git public_access:master
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: public_access
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: public_access